### ISSUE TITLE
konnectivity-agent and metrics-server fail to run on both Calico and Cilium (CAPI OpenStack)

### ISSUE THREAD

**Issue by febri4n** [k0sproject/k0smotron#1015]
### What happened?

I'm encountering an issue in my Kubernetes cluster where both the konnectivity-agent and metrics-server pods fail to run properly when using either Calico or Cilium as the CNI. This problem occurs consistently in the kube-system namespace.

### Involved Areas

Cluster API integration

### What did you expect to happen?

I expected both the konnectivity-agent and metrics-server pods to start successfully and reach the Running

### Steps to reproduce

This is my yaml file, i am using CAPI OpenStack
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: febri4n-capi-k0smotron-cp
spec:
  image: k0sproject/k0s
  version: v1.30.12-k0s.0
  replicas: 1
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: febri4n-capi-k0smotron-cluster-config
    spec:
      network:
        provider: custom
        kuberouter:
          disabled: true
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132
  persistence: {}
  etcd: {}
```
Cilium:
```bash
NAME                               READY   STATUS                       RESTARTS   AGE
cilium-envoy-qwh97                 1/1     Running                      0          6m3s
cilium-operator-6849c9c94c-4scdw   1/1     Running                      0          6m3s
cilium-z7jg9                       1/1     Running                      0          6m3s
coredns-5b4c6b9676-kjzhm           1/1     Running                      0          16m
konnectivity-agent-9xxk9           0/1     CreateContainerConfigError   0          15m
kube-proxy-dnchw                   1/1     Running                      0          15m
metrics-server-56964c6d44-rdc2n    0/1     Running                      0          16m
```
Calico
```bash
NAME                                           READY   STATUS                       RESTARTS   AGE 
pod/calico-kube-controllers-75bdb5b75d-wdvz9   1/1     Running                      0          3m11s
pod/calico-node-mnr5b                          1/1     Running                      0          3m11s
pod/coredns-5b4c6b9676-tkpj6                   1/1     Running                      0          6m59s
pod/konnectivity-agent-6xpd9                   0/1     CreateContainerConfigError   0          14s
pod/kube-proxy-gjl96                           1/1     Running                      0          5m58s
pod/metrics-server-56964c6d44-959cm            0/1     Running                      0          6m59s
```
I have already removed the following taint from the worker nodes:
```bash
node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
```

### k0smotron version

v1.5.2

### k0s version

v1.30.12-k0s.0

### Anything else we need to know?

Events on konnectivity-agent 
```bash
Events:
  Type     Reason           Age                    From               Message
  ----     ------           ----                   ----               -------
  Normal   Scheduled        44m                    default-scheduler  Successfully assigned kube-system/konnectivity-agent-9xxk9 to febri4n-capi-k0smotron-md-gj8pq-kghqz
  Warning  NetworkNotReady  39m (x152 over 44m)    kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Normal   Pulling          34m                    kubelet            Pulling image "quay.io/k0sproject/apiserver-network-proxy-agent:v0.30.3"
  Normal   Pulled           4m46s (x138 over 34m)  kubelet            Container image "quay.io/k0sproject/apiserver-network-proxy-agent:v0.30.3" already present on machine
```
Events on Metrics-server
```bash
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  46m                    default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  45m (x9 over 46m)      default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  34m (x2 over 39m)      default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Normal   Scheduled         34m                    default-scheduler  Successfully assigned kube-system/metrics-server-56964c6d44-rdc2n to febri4n-capi-k0smotron-md-gj8pq-kghqz
  Normal   Pulling           34m                    kubelet            Pulling image "registry.k8s.io/metrics-server/metrics-server:v0.7.2"
  Normal   Pulled            33m                    kubelet            Successfully pulled image "registry.k8s.io/metrics-server/metrics-server:v0.7.2" in 6.93s (17.545s including waiting). Image size: 19494617 bytes.
  Normal   Created           33m                    kubelet            Created container: metrics-server
  Normal   Started           33m                    kubelet            Started container metrics-server
  Warning  Unhealthy         3m57s (x201 over 33m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
```

**Comment by febri4n** [comment]
I am also rollout restart daemonset konnectivity-agent, and this is Events from konnectivity-agent pod.
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  66s               default-scheduler  Successfully assigned kube-system/konnectivity-agent-4b68p to febri4n-capi-k0smotron-md-h8sz8-x9zt2
  Normal   Pulled     4s (x8 over 66s)  kubelet            Container image "quay.io/k0sproject/apiserver-network-proxy-agent:v0.30.3" already present on machine
  Warning  Failed     4s (x8 over 66s)  kubelet            Error: host IP unknown; known addresses: []
```

**Comment by milkowski** [comment]
@febri4n You probably mean
```yaml
   apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: cilium-cluster-config
    spec:
      network:
        provider: custom
        kubeProxy:
          disabled: true
```
