### ISSUE TITLE
K0smotronControlPlane status.ready never becomes true when etcd field is partially configured

### ISSUE THREAD

**Issue by kahirokunn** [k0sproject/k0smotron#1047]
### What happened?

K0smotronControlPlane gets stuck in a reconciliation loop and its `.status.ready` field never becomes `true` when the `etcd` field is partially configured without the `resources` field.

The controller continuously keeps updating the k0smotron Cluster spec, preventing the reconciliation from completing. This issue started occurring from v1.5.3.

Reproduction in CI: https://github.com/k0sproject/k0smotron/actions/runs/15410066553/job/43360285044?pr=1046

### Involved Areas

Cluster API integration

### What did you expect to happen?

K0smotronControlPlane should reconcile successfully and `.status.ready` should become `true` when the cluster is ready, even when the etcd field is partially configured without explicitly defining the resources field.

### Steps to reproduce

1. Create a K0smotronControlPlane with partial etcd configuration:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: docker-test-cp
spec:
  version: v1.33.1-k0s.0
  etcd:
    autoDeletePVCs: true
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     cpu: 200m
    #     memory: 256Mi
  persistence:
    type: pvc
    persistentVolumeClaim:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
  service:
    type: NodePort
```

2. Apply the manifest
3. Check the controller logs: `kubectl logs -n k0smotron deployment/k0smotron-controller-manager`
4. Observe that:
   - `.status.ready` remains `false` indefinitely
   - The reconciliation loop continues

### k0smotron version

v1.5.3

### k0s version

v1.33.1-k0s.0

### Anything else we need to know?

**Root Cause**: The kubebuilder default annotation for the `Etcd` field doesn't include `resources`, causing `Etcd.Resources` to be initialized inconsistently (sometimes `nil`, sometimes `{}`). The `isClusterSpecEqual` function treats these as different values, triggering continuous spec updates.

**Workaround**: Explicitly define the resources field in the etcd configuration:
```yaml
etcd:
  autoDeletePVCs: false
  image: quay.io/k0sproject/etcd:v3.5.13
  resources: {}  # Add this line
```

**Impact**: This is a regression from v1.5.3 that prevents users from deploying K0smotronControlPlane with a common configuration pattern (partial etcd configuration).
