### ISSUE TITLE
MachineSet Preflight Checks fail due to version mismatch between K0smotronControlPlane spec.version and status.version

### ISSUE THREAD

**Issue by kahirokunn** [k0sproject/k0smotron#1052]
## What happened?

When using k0smotron with Cluster API's MachineSet Preflight Checks feature enabled, the `ControlPlaneIsStable` preflight check continuously fails, causing MachineDeployment scale-up operations to be held indefinitely.

Specifically, the K0smotronControlPlane has `spec.version` set to `v1.33.1` while `status.version` is `v1.33.1-k0s.0`. Due to this build metadata difference, Cluster API incorrectly determines that the control plane is "upgrading".

The following message is repeatedly logged every 15 seconds:
```
Scale up on hold because K0smotronControlPlane k0smotron-k1/k1-dhd6j is upgrading ("ControlPlaneIsStable" preflight check failed)
```

## Involved Areas

Cluster API integration

## What did you expect to happen?

When the K0smotronControlPlane is in a stable state, the `ControlPlaneIsStable` check in MachineSet Preflight Checks should pass, allowing MachineDeployment to scale up normally.

## Steps to reproduce

1. Prepare a Cluster API management cluster
2. Set up the environment with the following commands:

```bash
export CLUSTER_TOPOLOGY="true"
export EXP_RUNTIME_SDK="true"
export EXP_MACHINE_SET_PREFLIGHT_CHECKS="true"

clusterctl init \
  --bootstrap k0sproject-k0smotron \
  --control-plane k0sproject-k0smotron \
  --infrastructure k0sproject-k0smotron,docker \
  --core cluster-api
```

3. Create a cluster using k0smotron + Docker provider cluster class (see [documentation](https://github.com/k0sproject/k0smotron/blob/main/docs/capi-clusterclass.md))
Example:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test
spec:
  topology:
    class: k0smotron-docker-etcd
    classNamespace: k0smotron
    version: v1.33.1
    workers:
      machineDeployments:
        - class: docker-worker
          name: default
          replicas: 2
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
```

4. Create a MachineDeployment and attempt to scale up worker nodes
5. Check the capi-controller-manager logs

## k0smotron version

`quay.io/k0sproject/k0smotron:v1.5.3`

## k0s version

v1.33.1-k0s.0

## Anything else we need to know?

This issue is caused by Cluster API's `IsUpgrading` method detecting the build metadata difference (`v1.33.1` vs `v1.33.1-k0s.0`) when comparing `spec.version` and `status.version`, incorrectly determining that an upgrade is in progress. [1](#7-0)

**Important**: This issue is not limited to the MachineSet Preflight Checks feature. Since K0smotronControlPlane does not comply with Cluster API specifications, there is a risk of similar issues occurring in other features such as:

1. **Automatic upgrades in Cluster Topology**: As shown in [2](#7-1), control plane upgrade state determination is used

2. **Machine rollout determination in KubeadmControlPlane**: Version comparison logic like [3](#7-2)

3. **clusterctl move operations**: Provider version compatibility checks in [4](#7-3)

4. **Other features dependent on Cluster API contracts**: Potential issues in all features that perform version comparisons

As a solution, I propose normalizing the K0smotronControlPlane's `status.version` field to align with Cluster API standards, while storing the complete k0s-specific version information in a separate status field (e.g., `status.k0s.version`). This will ensure compatibility with the entire Cluster API ecosystem.

## Notes

With this fix, k0smotron will be able to properly integrate with all Cluster API features as a standard Cluster API control plane provider.
