### ISSUE TITLE
Controller bootstrap provider

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0smotron#127]
The bootstrap provider should be able to act as a provider also for the controllers. This way users can use k0smotron to also provision "traditional" clusters with dedicated controllers running on `Machine`s.

Looking at some of the other providers they always have a single `XYZConfig` style CRD that covers both the controller and worker setups.

**Comment by makhov** [comment]
So, basically, the plan is to add `spec.machineTemplate` field to the `K0smotronControlPlane` object. If it's non-nil, k0smotron creates:
- `XYZMachine` objects based on the template
- separate bootstrap secrets for machines (each machine should have its own join token) 
- `Machine` objects with corresponding `Machine.Spec.Bootstrap.DataSecretName` fields.

Does it make sense?

**Comment by jnummelin** [comment]
Pretty much, yes. Whether we want to do _within_ `K0smotronControlPlane` or as a separate CRD is debatable. (and we can alter that once we have bit better exposure to CP provider implementation details)

We need to create a separate `ControlPlane` provider for this use case. For example this is how the CAPI built-in KubeAdm provider is hooked up:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: my-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: my-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  region: eu-north-1
  sshKeyName: jnummelin
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: my-cluster-control-plane
  replicas: 1
  version: 1.27.3
```

See more about the contract for ControlPlane providers at https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html

For KubeAdm CP provider details see https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/controllers/controller.go#L138

I guess we can re-use some of the bits for Machine etc. creation.

**Comment by makhov** [comment]
So, we create the `K0sControlPlane` object like below, right?
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  k0sSpec:
    args: []
    preStartCommands: []
    postStartCommands: []
    preInstalledK0s: <bool>
    downloadURL: <string>
    config:
      <usual k0s config>
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: my-cluster-control-plane
  replicas: 1
  version: 1.27.3+k0s.0
```

I am a bit worried about having both `K0smotronControlPlane` and `K0sControlPlane`, but I agree, that it's better than try to do it in one object.
