### ISSUE TITLE
NodePort not picked automatically for more than 1 cluster

### ISSUE THREAD

**Issue by matti** [k0sproject/k0smotron#341]
https://docs.k0smotron.io/v0.7.0/resource-reference/#clusterspecservice says

"APIPort defines the kubernetes API port. If empty k0smotron will pick it automatically." 

It doesn't do it for another cluster

This works:

```
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: test-1
spec:
  service:
    type: NodePort
    apiPort:
    konnectivityPort:
```

Then this fails
```
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: test-2
spec:
  service:
    type: NodePort
    apiPort:
    konnectivityPort:
```

```
status.reconciliationStatus: Failed reconciling services
```

Or better yet, how to disable service completely? (#342)
