### ISSUE TITLE
Disable service completely

### ISSUE THREAD

**Issue by matti** [k0sproject/k0smotron#342]
Tried

```
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: test-1
spec:
  service: null
```

Doesn't work - how can I skip the service completely (I implement my own)
