### ISSUE TITLE
Clusterapi Capd k0smotron child cluster deployment problem

### ISSUE THREAD

**Issue by ozhankaraman** [k0sproject/k0smotron#381]
Hi, I followed the docs under docs/capi-docker.md to deploy a quickstart cluster to test k0smotron but I could not deploy it successfully, only docker-test-lb is deployed on docker but I could not get a cluster attached to this load balancer. Below are the exact steps that I executed. I am using kind cluster as parent cluster. I tried it with capi 1.6.0 and 1.5.3 but still I have the same problem

* Deploy kind cluster
```
cat <<EOF | kind create cluster --name="capi-test"  --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.27.3
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
EOF
``` 

* Deploy k0smotron and capi
```
kubectl apply -f https://docs.k0smotron.io/v0.7.2/install.yaml

export CLUSTER_TOPOLOGY=true
clusterctl init --core cluster-api:v1.5.3 --infrastructure docker:v1.5.3 --bootstrap kubeadm:v1.5.3 --control-plane kubeadm:v1.5.3
```

* Generate a sample cluster from the docs
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: docker-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: docker-test-cp
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: docker-test
    namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane # This is the config for the controlplane
metadata:
  name: docker-test-cp
  namespace: default
spec:
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: docker-test
  namespace: default
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron # This marks the base infra to be self managed. The value of the annotation is irrelevant, as long as there is a value.
spec: {}
  # More details of the DockerCluster can be set here
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name:  docker-test-md
  namespace: default
spec:
  clusterName: docker-test
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: docker-test
      pool: worker-pool-1
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: docker-test
        pool: worker-pool-1
    spec:
      clusterName: docker-test
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: docker-test-machine-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: docker-test-mt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: docker-test-mt
  namespace: default
spec:
  template:
    spec: {}
  # More details of the DockerMachineTemplate can be set here
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: docker-test-machine-config
spec:
  template:
    spec:
      version: v1.27.2+k0s.0
      # More details of the worker configuration can be set here
```

* docker running containers
```
root@capd4:~# docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                            NAMES
4289efce6f43   kindest/haproxy:v20230510-486859a6   "haproxy -W -db -f /…"   12 minutes ago   Up 12 minutes   0/tcp, 0.0.0.0:32769->6443/tcp   docker-test-lb
d3b079323ecf   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   15 minutes ago   Up 15 minutes   127.0.0.1:38255->6443/tcp        capi-test-control-plane
bad1202ac731   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   15 minutes ago   Up 15 minutes                                    capi-test-worker
```

* cluster and machine status?
```
root@capd4:~# kubectl get cluster,machine
NAME                                   PHASE         AGE   VERSION
cluster.cluster.x-k8s.io/docker-test   Provisioned   13m

NAME                                                  CLUSTER       NODENAME   PROVIDERID   PHASE     AGE   VERSION
machine.cluster.x-k8s.io/docker-test-md-nvrj4-5867k   docker-test                           Pending   13m
```

* machine status
```
root@capd4:~# kubectl describe machine.cluster.x-k8s.io/docker-test-md-nvrj4-5867k
Name:         docker-test-md-nvrj4-5867k
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=docker-test
              cluster.x-k8s.io/deployment-name=docker-test-md
              cluster.x-k8s.io/set-name=docker-test-md-nvrj4
              machine-template-hash=1043256921-nvrj4
              pool=worker-pool-1
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Machine
Metadata:
  Creation Timestamp:  2023-12-19T15:42:19Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generation:  1
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineSet
    Name:                  docker-test-md-nvrj4
    UID:                   7ce0c69f-752c-4fb5-b6b6-dbd5b3a43dbb
  Resource Version:        1494
  UID:                     24406b02-9003-47ae-a897-6e258d8dadd8
Spec:
  Bootstrap:
    Config Ref:
      API Version:  bootstrap.cluster.x-k8s.io/v1beta1
      Kind:         K0sWorkerConfig
      Name:         docker-test-machine-config-77t5c
      Namespace:    default
      UID:          848eedd5-6d1f-449a-be43-f438e349b899
  Cluster Name:     docker-test
  Infrastructure Ref:
    API Version:          infrastructure.cluster.x-k8s.io/v1beta1
    Kind:                 DockerMachine
    Name:                 docker-test-mt-n4kpv
    Namespace:            default
    UID:                  14cc6555-1730-4fad-83f7-1b4f17e30cb5
  Node Deletion Timeout:  10s
Status:
  Conditions:
    Last Transition Time:  2023-12-19T15:42:20Z
    Message:               0 of 2 completed
    Reason:                WaitingForControlPlaneAvailable
    Severity:              Info
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-12-19T15:42:19Z
    Reason:                WaitingForDataSecret
    Severity:              Info
    Status:                False
    Type:                  BootstrapReady
    Last Transition Time:  2023-12-19T15:42:20Z
    Message:               0 of 2 completed
    Reason:                WaitingForControlPlaneAvailable
    Severity:              Info
    Status:                False
    Type:                  InfrastructureReady
    Last Transition Time:  2023-12-19T15:42:19Z
    Reason:                WaitingForNodeRef
    Severity:              Info
    Status:                False
    Type:                  NodeHealthy
  Last Updated:            2023-12-19T15:42:19Z
  Observed Generation:     1
  Phase:                   Pending
Events:                    <none>
root@capd4:~#
```

* I could not find what I am missing here? I also tried to deploy k0smotron by clusterctl cli but cli could not find bootstrap-components.yaml and other components for release v0.7.2, It gives error below:
```
root@capd4:~# clusterctl init --bootstrap k0smotron --control-plane k0smotron --config config.yaml
Fetching providers
Error: failed to get provider components for the "k0smotron" provider: failed to read "bootstrap-components.yaml" from provider's repository "bootstrap-k0smotron": failed to download files from GitHub release v0.7.2: failed to get file "bootstrap-components.yaml" from "v0.7.2" release
root@capd4:~# cat config.yaml
providers:
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/control-plane-components.yaml"
    type: "ControlPlaneProvider"
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/infrastructure-components.yaml"
    type: "InfrastructureProvider"
root@capd4:~# clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"14efefeb46dbe8d0cd0f5b7d1718e00ec58fc079", GitTreeState:"clean", BuildDate:"2023-12-05T17:59:05Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
root@capd4:~#
```

* I am really blocked here :) thanks for all replies

**Comment by makhov** [comment]
Hello! 

I've checked the same config on my local cluster and couldn't reproduce the issue. Could you please provide k0smotron logs and also check if there is a control-plane pod and it's state?

Regarding the clusterctl support, it's been merged but hasn't released yet. Should be available since the next release.

**Comment by ozhankaraman** [comment]
Hi!

Thanks for your prompt reply, I redeployed all stuff now, I am using Kind cluster 1.27.3 here and all pods status is in Running state and they are listed as below. I waited 10 minutes after deploying sample cluster over Kind

```
root@capd4:~# k get pods -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capd-system                         capd-controller-manager-56d89d9c67-bjz9j                         1/1     Running   0          12m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-557b778d6b-q59gn       1/1     Running   0          12m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-55d8f6b576-2kvq9   1/1     Running   0          12m
capi-system                         capi-controller-manager-58cbb8f944-4pb5n                         1/1     Running   0          12m
cert-manager                        cert-manager-6954d7bbbf-znt8z                                    1/1     Running   0          13m
cert-manager                        cert-manager-cainjector-84bdff4846-2h5z4                         1/1     Running   0          13m
cert-manager                        cert-manager-webhook-85b6b76d9b-2xt6n                            1/1     Running   0          13m
default                             kmc-docker-test-cp-0                                             1/1     Running   0          10m
k0smotron                           k0smotron-controller-manager-56cfcf855f-rftk2                    2/2     Running   0          13m
kube-system                         coredns-5d78c9869d-hl8lh                                         1/1     Running   0          13m
kube-system                         coredns-5d78c9869d-kpsrq                                         1/1     Running   0          13m
kube-system                         etcd-capi-test-control-plane                                     1/1     Running   0          13m
kube-system                         kindnet-bfq4r                                                    1/1     Running   0          13m
kube-system                         kindnet-x26gg                                                    1/1     Running   0          13m
kube-system                         kube-apiserver-capi-test-control-plane                           1/1     Running   0          13m
kube-system                         kube-controller-manager-capi-test-control-plane                  1/1     Running   0          13m
kube-system                         kube-proxy-s4tkw                                                 1/1     Running   0          13m
kube-system                         kube-proxy-zvkrd                                                 1/1     Running   0          13m
kube-system                         kube-scheduler-capi-test-control-plane                           1/1     Running   0          13m
local-path-storage                  local-path-provisioner-6bc4bddd6b-9lhln                          1/1     Running   0          13m
root@capd4:~# k get cluster,machine
NAME                                   PHASE         AGE   VERSION
cluster.cluster.x-k8s.io/docker-test   Provisioned   10m

NAME                                                  CLUSTER       NODENAME   PROVIDERID   PHASE     AGE   VERSION
machine.cluster.x-k8s.io/docker-test-md-4628h-szq26   docker-test                           Pending   10m
root@capd4:~# docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                            NAMES
8037f4932a18   kindest/haproxy:v20230510-486859a6   "haproxy -W -db -f /…"   10 minutes ago   Up 10 minutes   0/tcp, 0.0.0.0:32770->6443/tcp   docker-test-lb
8af87da49b1e   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   14 minutes ago   Up 14 minutes                                    capi-test-worker
ac663f96ae7c   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   14 minutes ago   Up 14 minutes   127.0.0.1:41221->6443/tcp        capi-test-control-plane
```

* Logs for capd-controller-manager-56d89d9c67-bjz9j https://pastebin.com/UKAm3FAW
* Logs for capi-controller-manager-58cbb8f944-4pb5n https://pastebin.com/QDNFRxGt
* Logs for capi-kubeadm-bootstrap-controller-manager-557b778d6b-q59gn https://pastebin.com/GnGMUxY3
* Logs for k0smotron-controller-manager-56cfcf855f-rftk2 https://pastebin.com/6HbhMCvJ
* Logs for kmc-docker-test-cp-0 https://pastebin.com/eNpYMciG

**Comment by makhov** [comment]
Could you also show me a k0smotron Cluster object? The operator complains, that it's missing
```
kubectl get clusters.k0smotron.io docker-test-cp -o yaml
```

**Comment by ozhankaraman** [comment]
Hi, output is below
```
oot@capd4:~# kubectl get clusters.k0smotron.io docker-test-cp -o yaml
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-12-20T11:26:30Z"
  generation: 2
  labels:
    cluster.x-k8s.io/cluster-name: docker-test
  name: docker-test-cp
  namespace: default
  ownerReferences:
  - apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: docker-test-cp
    uid: 8525375b-bf0a-4486-83fb-7cb33f7eb72c
  resourceVersion: "17863"
  uid: 83292417-b77e-4420-bf07-b80e58c08399
spec:
  certificateRefs:
  - name: docker-test-ca
    type: ca
  - name: docker-test-proxy
    type: proxy
  - name: docker-test-sa
    type: sa
  externalAddress: 172.18.0.3
  k0sImage: k0sproject/k0s
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  replicas: 1
  resources: {}
  service:
    apiPort: 30443
    konnectivityPort: 30132
    type: NodePort
status:
  reconciliationStatus: Reconciliation successful
 ```

**Comment by makhov** [comment]
Thanks for your help, looks like we found a bug in k0smotron! 

Some name usages are not uniformed, that's why it requests for some wrong objects. I'm looking into it and will try to fix it asap.

As a workaround you can rename `K0smotronControlPlane`'s name to the same name as `Cluster` has (in your example, it's `docker-test`).

**Comment by ozhankaraman** [comment]
Hi;

I applied the workaround I passed that step and machinedeployment comes from provisioning to ScalingUp but after 15 minutes passed there are no control plane or worker node containers on docker. Latest status is below, looks like  issue still remains with workaround

```
root@capd4:~# k get cluster,machinedeployment
NAME                                   PHASE         AGE   VERSION
cluster.cluster.x-k8s.io/docker-test   Provisioned   15m

NAME                                                CLUSTER       REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE   VERSION
machinedeployment.cluster.x-k8s.io/docker-test-md   docker-test   1                  1         1             ScalingUp   15m
```

* Latest child cluster manifest
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: docker-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: docker-test
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: docker-test
    namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane # This is the config for the controlplane
metadata:
  name: docker-test
  namespace: default
spec:
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: docker-test
  namespace: default
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron # This marks the base infra to be self managed. The value of the annotation is irrelevant, as long as there is a value.
spec: {}
  # More details of the DockerCluster can be set here
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name:  docker-test-md
  namespace: default
spec:
  clusterName: docker-test
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: docker-test
      pool: worker-pool-1
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: docker-test
        pool: worker-pool-1
    spec:
      clusterName: docker-test
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: docker-test-machine-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: docker-test-mt
 ---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: docker-test-mt
  namespace: default
spec:
  template:
    spec: {}
  # More details of the DockerMachineTemplate can be set here
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: docker-test-machine-config
spec:
  template:
    spec:
      version: v1.27.2+k0s.0
      # More details of the worker configuration can be set here
root@capd4:~
````

* docker running container list
```
root@capd4:~# docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                            NAMES
b441a7a17116   kindest/haproxy:v20230510-486859a6   "haproxy -W -db -f /…"   17 minutes ago   Up 17 minutes   0/tcp, 0.0.0.0:32771->6443/tcp   docker-test-lb
8af87da49b1e   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   5 hours ago      Up 5 hours                                       capi-test-worker
ac663f96ae7c   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   5 hours ago      Up 5 hours      127.0.0.1:41221->6443/tcp        capi-test-control-plane
root@capd4:~#
```

* Pod Logs uploaded to : https://www.zebrastack.com/tmp/output.txt

**Comment by makhov** [comment]
Note, that we create a docker network for kind with `--opt com.docker.network.bridge.enable_ip_masquerade=true`.
https://github.com/k0sproject/k0smotron/blob/main/.github/workflows/go.yml#L154

If you didn't do it, this might be a reason

**Comment by ozhankaraman** [comment]
Hi, even you do not create docker network individually, kind creates it's own network with com.docker.network.bridge.enable_ip_masquerade=true settings. I also redeployed my cluster by creating network individually and it's same result.

* After investigating inttest directory I find a working example as below on my kind cluster
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: docker-md-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: docker-md-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: docker-md-test
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: docker-md-test
spec:
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: docker-md-test
  namespace: default
spec:
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: docker-md-test
  namespace: default
spec:
  replicas: 2
  clusterName: docker-md-test
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: docker-md-test
      pool: worker-pool-1
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: docker-md-test
        pool: worker-pool-1
    spec:
      version: v1.27.2
      clusterName: docker-md-test
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: docker-md-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: docker-md-test
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: docker-md-test
  namespace: default
spec:
  template:
    spec:
      version: v1.27.2+k0s.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: docker-md-test
  namespace: default
spec:
  template:
    spec: {}
```

* but the below one with your recommended workaround does not work,

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: docker-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: docker-test
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: docker-test
    namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane # This is the config for the controlplane
metadata:
  name: docker-test
  namespace: default
spec:
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: docker-test
  namespace: default
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron # This marks the base infra to be self managed. The value of the annotation is irrelevant, as long as there is a value.
spec: {}
  # More details of the DockerCluster can be set here
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name:  docker-test-md
  namespace: default
spec:
  clusterName: docker-test
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: docker-test
      pool: worker-pool-1
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: docker-test
        pool: worker-pool-1
    spec:
      clusterName: docker-test
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: docker-test-machine-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: docker-test-mt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: docker-test-mt
  namespace: default
spec:
  template:
    spec: {}
  # More details of the DockerMachineTemplate can be set here
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: docker-test-machine-config
spec:
  template:
    spec:
      version: v1.27.2+k0s.0
      # More details of the worker configuration can be set here
```
