### ISSUE TITLE
Ingress solution

### ISSUE THREAD

**Issue by juanluisvaladas** [k0sproject/k0smotron#4]
Currently the implementation only allows nodePort and what's worse, it has the port hardcoded.

We need an ingress solution that at minimum allows to choose:
* No ingress at all (user will solve this manually)
* NodePort Service

In the future it would be good to either use the gateway API or to have one load balancer managed by k0smotron.

**Comment by cwrau** [comment]
Heyho, is it possible to reopen this now? We're also looking into using DNS for the clusters instead of IPs for everything.

Currently it looks like we can just use the ClusterIP service, set k0smotronControlPlane.spec.externalAddress to the DNS name and then create the Ingress ourselves using one of the generated tls secrets for TLS, is that correct?

**Comment by juanluisvaladas** [comment]
Hi @cwrau, it's not really a good moment to have this discussion because relevant people are on vacation.
I've reopened it and, when people are back we'll review this.

**Comment by jnummelin** [comment]
The challenge is not how to expose the hosted controlplane via Ingress, that part is pretty "trivial". Famous last words... 😂 

The main challenge is, how do we configure the child clusters internals to understand the Ingress. So if we look at any cluster, there's always the internal API svc, in defaul k0s configs it's using `10.96.0.1` address. So how do we configure that to route to the Ingress?

**Comment by mrik974** [comment]
Hi, my two cents about this. I've been following multiple implementations of containerized control planes, and I've found one at a french provider, which is very interesting but needs a couple of changes in the way the node is configured. I've implemented it in a proof of concept some time ago.

I believe I can try and implement it manually with K0smotron, but I have never used K0smotron before. I just stumbled upon your project and it is very promising. Here's how they did it, let me know what you think about it.

- On control plane side, they create a TCP route with a Host SNI rule, with no TLS passthrough.
- On node side, they did two things : 
  - Added a fake netdev device taking the default IP of the cluster (`10.96.0.1`)
  - Added a DaemonSet with a simple HAProxy listening on that netdev and transferring packets to the control plane via the TCP route.

Here's what it looks like schematically.

<img width="1232" height="732" alt="Image" src="https://github.com/user-attachments/assets/acf8eb12-8d0b-4bda-ac7c-70c08842c08e" />

**Comment by makhov** [comment]
@mrik974 thank you for the kind words! Yeah, that's basically the same idea that I use in #1175. I'm still testing and polishing the code, but I managed to have it up and running (with corresponding changes on the k0s side, see https://github.com/k0sproject/k0s/pull/6204)

**Comment by mrik974** [comment]
If I get it right, k0s was already proxying the kubernetes IP on each node and now with your PR it will support DNS instead of only IP, setting up a haproxy on each node, which will enable the use of Ingress with TLS SNI ? That's excellent news ! 
I see the default setting will be SSLPassthrough=true. 
I'm not an expert in HAProxy but does your configuration mean "do not verify with the domain certificate, but verify with the cluster api certificate, while keeping the SNI header correctly set ?

**Comment by kahirokunn** [comment]
@makhov First of all, thank you for adding Ingress support — that’s really great to see! 🙌 

https://github.com/k0sproject/k0smotron/issues/4#issue-1642864442
> In the future it would be good to either use the Gateway API or to have one load balancer managed by k0smotron.

I was also wondering if you could share what the current plan is regarding Gateway API support. 👀 

Thank you. 🙏

**Comment by makhov** [comment]
I took a look on the Gateway API status and it's implementations and I don't think we can reliably support it in its current state. TLSRoute and TCPRoute are both experimental and don't exist in v1, TCPRoute doesn't support hostnames (or maybe it does via configuring hostname in the listeners), TLSRoute is not supported by many major implementations, and tbh I don't see much difference between those two. 

What I think I can do, is to add some knob that says k0smotron to configure everything but not to deploy Ingress resource and let the end-user configure it manually.

**Comment by mrik974** [comment]
I agree with that one, as a Traefik user, I'd personnally prefer using their IngressRoute CRD :). So letting the user choose how he wants to Ingress is a cool idea to me.

**Comment by kahirokunn** [comment]
@makhov  Thanks for the explanation. 🙏 
How about HTTPRoute in this case? I was thinking of something along these lines with BackendTLSPolicy:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${hcp}-api
  namespace: ${hcp-ns}
spec:
  parentRefs:
  - kind: Gateway
    name: kmc-gw-0001
    namespace: infra-gw
    sectionName: ${hcp}-api
  rules:
  - backendRefs:
    - name: kmc-${hcp}-api
      port: 32443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: ${hcp}-api-backend-tls
  namespace: ${hcp-ns}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kmc-${hcp}-api
  validation:
    hostname: api-internal.${hcp}.svc.cluster.local
    caCertificateRefs:
      - kind: ConfigMap
        name: ${hcp}-ca-bundle
```

Would this still fall into the same issues you pointed out earlier, or do you see this as a viable option? 👀
