### ISSUE TITLE
Usage "Remote Machine Provider"

### ISSUE THREAD

**Issue by tdesaules** [k0sproject/k0smotron#539]
Hello K0smotron team,

I'm trying a small lab with some "bar metal" AArch64 SBC.

I'm trying to follow this : [https://www.youtube.com/watch?v=7U8BHHZ-LLQ&list=WL&index=3](https://www.youtube.com/watch?v=7U8BHHZ-LLQ&list=WL&index=3)

With a single node "mothership" and a "worker".

Just taking the exact conf from : [https://docs.k0smotron.io/stable/capi-remote/](https://docs.k0smotron.io/stable/capi-remote/)
Using K0s version v1.29.3+k0s.0 and k0smotron v0.9.0

But I have some "ref" issue like

```
[...]
resource mapping not found for name: "remote-test" namespace: "default" from "cp-test.yml": no matches for kind "Cluster" in version "cluster.x-k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "remote-test-0" namespace: "default" from "cp-test.yml": no matches for kind "Machine" in version "cluster.x-k8s.io/v1beta1"
ensure CRDs are installed first
[...]
```

I'm I missing something ?

the yml file used : 

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: remote-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: remote-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: remote-test
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: remote-test
  namespace: default
spec:
  version: v1.29.3+k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteCluster
metadata:
  name: remote-test
  namespace: default
spec:
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name:  remote-test-0
  namespace: default
spec:
  clusterName: remote-test
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: remote-test-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: remote-test-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: remote-test-0
  namespace: default
spec:
  version: v1.29.3+k0s.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: remote-test-0
  namespace: default
spec:
  address: 192.168.1.116
  port: 22
  user: kamisound
  sshKeyRef:
    name: k0smotron-ssh-key
```

**Comment by makhov** [comment]
Hi! Have you installed CAPI core components CRDs?

**Comment by tdesaules** [comment]
Hi ! Correct... I was convinced I had passed them, I must have missed something, I will look into it during the day to check that.

**Comment by tdesaules** [comment]
Okay, I guess I must have forgotten it...

I reset the k0s cluster and started from scratch : 

Install k0s

```bash
kamisound in 🌐 mothership in ~ 
❯ curl -sSLf https://get.k0s.sh | sudo sh
Downloading k0s from URL: https://github.com/k0sproject/k0s/releases/download/v1.29.4+k0s.0/k0s-v1.29.4+k0s.0-arm64
k0s is now executable in /usr/local/bin

kamisound in 🌐 mothership in ~ took 12s 
❯ sudo k0s install controller --single

kamisound in 🌐 mothership in ~ took 2s 
❯ sudo systemctl daemon-reload

kamisound in 🌐 mothership in ~ 
❯ sudo k0s start

kamisound in 🌐 mothership in ~ 
❯ sudo k0s status
Version: v1.29.4+k0s.0
Process ID: 2031
Role: controller
Workloads: true
SingleNode: true
Kube-api probing successful: true
Kube-api probing last error:

kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl get nodes
NAME         STATUS   ROLES           AGE   VERSION
mothership   Ready    control-plane   37s   v1.29.4+k0s

kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl get all -A
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-6cd46fb86c-qmxt2          1/1     Running   0          95s
kube-system   pod/kube-proxy-ss4ws                  1/1     Running   0          86s
kube-system   pod/kube-router-qq2lb                 1/1     Running   0          86s
kube-system   pod/metrics-server-7556957bb7-vvjxv   1/1     Running   0          95s

NAMESPACE     NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes       ClusterIP   10.96.0.1       <none>        443/TCP                  2m4s
kube-system   service/kube-dns         ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   114s
kube-system   service/metrics-server   ClusterIP   10.101.130.68   <none>        443/TCP                  106s

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kube-proxy    1         1         1       1            1           kubernetes.io/os=linux   115s
kube-system   daemonset.apps/kube-router   1         1         1       1            1           <none>                   115s

NAMESPACE     NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns          1/1     1            1           115s
kube-system   deployment.apps/metrics-server   1/1     1            1           106s

NAMESPACE     NAME                                        DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-6cd46fb86c          1         1         1       95s
kube-system   replicaset.apps/metrics-server-7556957bb7   1         1         1       95s
```

And k0smotron

```bash
kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl apply -f https://docs.k0smotron.io/v0.9.2/install.yaml
namespace/k0smotron created
customresourcedefinition.apiextensions.k8s.io/clusters.k0smotron.io created
customresourcedefinition.apiextensions.k8s.io/jointokenrequests.k0smotron.io created
customresourcedefinition.apiextensions.k8s.io/k0scontrollerconfigs.bootstrap.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0scontrollerconfigs.controlplane.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0scontrolplanes.controlplane.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0scontrolplanetemplates.controlplane.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0smotroncontrolplanes.controlplane.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0smotroncontrolplanetemplates.controlplane.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0sworkerconfigs.bootstrap.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/k0sworkerconfigtemplates.bootstrap.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/pooledremotemachines.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/remoteclusters.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/remotemachines.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/remotemachinetemplates.infrastructure.cluster.x-k8s.io created
serviceaccount/k0smotron-controller-manager created
role.rbac.authorization.k8s.io/k0smotron-leader-election-role created
clusterrole.rbac.authorization.k8s.io/k0smotron-manager-role created
clusterrole.rbac.authorization.k8s.io/k0smotron-metrics-reader created
clusterrole.rbac.authorization.k8s.io/k0smotron-proxy-role created
rolebinding.rbac.authorization.k8s.io/k0smotron-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/k0smotron-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/k0smotron-proxy-rolebinding created
service/k0smotron-controller-manager-metrics-service created
deployment.apps/k0smotron-controller-manager created

kamisound in 🌐 mothership in ~ took 4s 
❯ curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.7.0/clusterctl-linux-arm64 -o clusterctl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 78.1M  100 78.1M    0     0  17.7M      0  0:00:04  0:00:04 --:--:-- 22.2M

kamisound in 🌐 mothership in ~ took 4s 
❯ sudo install -o root -g root -m 0755 clusterctl /usr/local/bin/clusterctl

kamisound in 🌐 mothership in ~ 
❯ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"ce58362fefb10c2c9e462a9a6c850733f4d87161", GitTreeState:"clean", BuildDate:"2024-04-16T17:12:56Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/arm64"}

kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubeconfig admin > .kube/config

kamisound in 🌐 mothership in ~ 
❯ clusterctl init --bootstrap k0sproject-k0smotron --control-plane k0sproject-k0smotron --infrastructure k0sproject-k0smotron
Fetching providers
Installing cert-manager Version="v1.14.4"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.7.1" TargetNamespace="capi-system"
Installing Provider="bootstrap-k0sproject-k0smotron" Version="v0.9.2" TargetNamespace="k0smotron"
Installing Provider="control-plane-k0sproject-k0smotron" Version="v0.9.2" TargetNamespace="k0smotron"
Installing Provider="infrastructure-k0sproject-k0smotron" Version="v0.9.2" TargetNamespace="k0smotron"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl generate cluster [name] --kubernetes-version [version] | kubectl apply -f -
```

So, it's better than before. But I still have an issue with the control plane pod.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: remote-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: remote-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: remote-test
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: remote-test
  namespace: default
spec:
  version: v1.29.4-k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteCluster
metadata:
  name: remote-test
  namespace: default
spec:
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name:  remote-test-0
  namespace: default
spec:
  clusterName: remote-test
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: remote-test-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: remote-test-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: remote-test-0
  namespace: default
spec:
  version: v1.29.4+k0s.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: remote-test-0
  namespace: default
spec:
  address: 192.168.1.116
  port: 22
  user: kamisound
  sshKeyRef:
    name: k0smotron-ssh-key
```

I create the secret and apply

```bash
kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl create secret generic k0smotron-ssh-key --from-file=value=/home/kamisound/.ssh/id_ed25519
secret/k0smotron-ssh-key created

kamisound in 🌐 mothership in ~ took 10s  
❯ sudo k0s kubectl apply -f remote-test.yml 
cluster.cluster.x-k8s.io/remote-test created
k0smotroncontrolplane.controlplane.cluster.x-k8s.io/remote-test created
remotecluster.infrastructure.cluster.x-k8s.io/remote-test created
machine.cluster.x-k8s.io/remote-test-0 created
k0sworkerconfig.bootstrap.cluster.x-k8s.io/remote-test-0 created
remotemachine.infrastructure.cluster.x-k8s.io/remote-test-0 created

kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl get all -n default
NAME                    READY   STATUS    RESTARTS   AGE
pod/kmc-remote-test-0   1/1     Running   0          7m1s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                           AGE
service/kmc-remote-test-nodeport   NodePort    10.102.158.21   <none>        30443:30443/TCP,30132:30132/TCP   7m1s
service/kubernetes                 ClusterIP   10.96.0.1       <none>        443/TCP                           2d4h

NAME                               READY   AGE
statefulset.apps/kmc-remote-test   1/1     7m1s
```

But the pod seems to have an issue.

```bash
kamisound in 🌐 mothership in ~ 
❯ sudo k0s kubectl describe pod kmc-remote-test-0
Name:             kmc-remote-test-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             mothership/192.168.1.115
Start Time:       Wed, 24 Apr 2024 22:29:51 +0200
Labels:           app=k0smotron
                  apps.kubernetes.io/pod-index=0
                  cluster=remote-test
                  cluster.x-k8s.io/cluster-name=remote-test
                  controller-revision-hash=kmc-remote-test-7469d47b
                  statefulset.kubernetes.io/pod-name=kmc-remote-test-0
Annotations:      <none>
Status:           Running
IP:               10.244.0.32
IPs:
  IP:           10.244.0.32
Controlled By:  StatefulSet/kmc-remote-test
Init Containers:
  certs-init:
    Container ID:  containerd://22c7d3f8366f928726f8caa2fd3e9a7b054f8764c3a4a6af1081226d7789760b
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      mkdir -p /var/lib/k0s/pki && cp /certs-init/*.* /var/lib/k0s/pki/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 24 Apr 2024 22:29:54 +0200
      Finished:     Wed, 24 Apr 2024 22:29:54 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /certs-init from certs (rw)
      /var/lib/k0s from kmc-remote-test (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kj7lg (ro)
Containers:
  controller:
    Container ID:  containerd://3c4f28158018d3450d2baf2e50e0b736716de7911dc2a296d54ebc033ee67a41
    Image:         k0sproject/k0s:v1.29.4-k0s.0
    Image ID:      docker.io/k0sproject/k0s@sha256:aae383638f0abeb40adce3179f91010288fc8dbe48a3d4692a8ef5758a00966b
    Ports:         30443/TCP, 30132/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /k0smotron-entrypoint.sh
    State:          Running
      Started:      Wed, 24 Apr 2024 22:29:55 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       exec [k0s status] delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      exec [k0s status] delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      kmc-remote-test-config  ConfigMap  Optional: false
    Environment:              <none>
    Mounts:
      /k0smotron-entrypoint.sh from kmc-entrypoint-remote-test-config (rw,path="k0smotron-entrypoint.sh")
      /var/lib/k0s from kmc-remote-test (rw)
      /var/lib/k0s/manifests/k0s-telemetry from kmc-remote-test-telemetry-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kj7lg (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kmc-entrypoint-remote-test-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kmc-entrypoint-remote-test-config
    Optional:  false
  certs:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          remote-test-ca
    SecretOptionalName:  <nil>
    SecretName:          remote-test-proxy
    SecretOptionalName:  <nil>
    SecretName:          remote-test-sa
    SecretOptionalName:  <nil>
  kmc-remote-test:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kmc-remote-test-telemetry-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kmc-remote-test-telemetry-config
    Optional:  false
  kube-api-access-kj7lg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  8m12s                  default-scheduler  Successfully assigned default/kmc-remote-test-0 to mothership
  Normal   Pulling    8m11s                  kubelet            Pulling image "busybox"
  Normal   Pulled     8m11s                  kubelet            Successfully pulled image "busybox" in 813ms (813ms including waiting)
  Normal   Created    8m11s                  kubelet            Created container certs-init
  Normal   Started    8m10s                  kubelet            Started container certs-init
  Normal   Pulled     8m10s                  kubelet            Container image "k0sproject/k0s:v1.29.4-k0s.0" already present on machine
  Normal   Created    8m10s                  kubelet            Created container controller
  Normal   Started    8m9s                   kubelet            Started container controller
  Warning  Unhealthy  7m41s (x3 over 8m1s)   kubelet            Readiness probe failed: command "k0s status" timed out
  Warning  Unhealthy  7m41s (x2 over 7m51s)  kubelet            Liveness probe failed: command "k0s status" timed out
```

**Comment by makhov** [comment]
Thanks for the details! Could you also show the status fields of the RemoteMachine (`kubectl get remotemachine -n default remote-test-0 -o yaml`) and k0smotron controller logs?

**Comment by tdesaules** [comment]
Well after some test it look like that part cause the issue : 

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: remote-test-0
  namespace: default
spec:
  address: 192.168.1.116
  port: 22
  user: kamisound
  sshKeyRef:
    name: k0smotron-ssh-key
```

The "kamisound" user doesn't work, switching "root" solve this.

I was sure to see somewhere that "sudo" passwordless account should work, no ?

**Comment by makhov** [comment]
```
Downloading k0s from URL: https://github.com/k0sproject/k0s/releases/download/v1.29.4+k0s.0/k0s-v1.29.4+k0s.0-arm64", "error": "command failed: client exec: ssh session wait: Process exited with status 2
```

Looks like k0smotron can't download k0s binary. There is a known issue with GitHub releases, sometimes it blocks automated downloads. Could you try this configuration? 

```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: remote-test-0
  namespace: default
spec:
  version: v1.29.4+k0s.0
  downloadURL: https://get.k0sproject.io/v1.29.4+k0s.0/k0s-v1.29.4+k0s.0-arm64
```
