### ISSUE TITLE
How to join kubeadm compute-plane?

### ISSUE THREAD

**Issue by cwrau** [k0sproject/k0smotron#575]
We're trying to run a k0smotron control-plane with a normal OpenStack cluster, see https://github.com/teutonet/teutonet-helm-charts/pull/962 for implementation, but the compute-plane can't join, getting `401 unauthorized ` from the API.

I thought maybe it's the missing cluster-info configmap and the missing RBAC for it, but I'm not quite sure and I also didn't want to just create the RBAC. I guess I just did something wrong 😅

The used values are the following;

```yaml
cloud: ffm3-dev
version:
  major: 1
  minor: 28
  patch: 9
controlPlane:
  hosted: true
metadata:
  serviceLevelAgreement: None
  customerID: 6969
  customerName: cwr
nodePools:
  compute-plane-1:
    replicas: 2
    flavor: standard.2.1905
```

If needed I can also provide the templated yamls.
