### ISSUE TITLE
K0smotron CAPI BYOCNI

### ISSUE THREAD

**Issue by xinity** [k0sproject/k0smotron#642]
I've been wondering how to use K0smotron CAPI provider to be able to use cilium or calico instead of kube-router.
The official documentation doesn't have any hints on this :(

Is it possible ?

**Comment by jnummelin** [comment]
so the CAPI controlplane object has "embedded" k0s config. In that config you can set `spec.network.provider: custom` and then BYOCNI.

One way to do that is to utilize [cluster resource set](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-resource-set)

**Comment by pv-aiuta-com** [comment]
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: myname
  namespace: default
spec:
  version: v1.32.3
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    spec:
      network:
        provider: calico
        calico:
          wireguard: true
```
