### ISSUE TITLE
Add ContentFrom option for Files configuration in K0sConfigSpec and K0sWorkerConfigSpec

### ISSUE THREAD

**Issue by a13x5** [k0sproject/k0smotron#692]
## Request 

`ContentFrom` option should be added to bootstrap API to give an ability to reference secret content as a file for cloud-init configuration.

The same functionality is present in [KubeadmConfig](https://github.com/kubernetes-sigs/cluster-api/blob/88c757fa5e2308eedacb100213b00b805bc732a3/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L525) for CAPI kubeadm bootstrap provider.

## Rationale 

Some infrastructure providers (like Azure CAPI provider) are using this functionality to pass infrastructure specific configuration to all nodes. In case of CAPZ the dynamically generated `azure.json` from the `Secret` object to all nodes. This file is required for CCM to function properly.

Example gist of `contentFrom` usage for kubeadm+azure:

```yaml
    files:
    - contentFrom:
        secret:
          key: control-plane-azure.json
          name: az-test-control-plane-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
```

Documentation reference for Azure provider is [here](https://capz.sigs.k8s.io/topics/cloud-provider-config)
