### ISSUE TITLE
Clarify docs on k0sConfig field

### ISSUE THREAD

**Issue by nealf** [k0sproject/k0smotron#727]
The [configuration page](https://docs.k0smotron.io/stable/configuration/) for standalone mode isn't clear about what needs to be included in the `k0sConfig` field. It took a little while to realize we needed to add a full ClusterConfig definition like the following instead of just the `spec` portion:

```yaml
spec:
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: custom
```

It might help others to mention that, and I'm happy to open a PR for that if you'd like.
