### ISSUE TITLE
Question about HA, etcd, and Kine

### ISSUE THREAD

**Issue by franpog859** [k0sproject/k0smotron#810]
I want to create an HA k0smotron setup, particularly the storage and the API server. To achieve an HA API Server I need to have at least 3 replicas of the k0smotron control plane, so:
```yaml
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: k0smotron-test
spec:
  replicas: 3
```
I [see the etcd configuration](https://docs.k0smotron.io/head/etcd/#customizing-etcd-configuration) that suggests it's possible to achieve storage HA with the etcd without any custom Kine setup. On the other hand, I [see that the Kine setup is required for replicas > 1](https://docs.k0smotron.io/head/resource-reference/?h=cluster#k0smotroncontrolplanespec). I'm confused. Could you elaborate on the possibilities for HA API Server and HA storage?
