### ISSUE TITLE
cluster name in kubeconfig

### ISSUE THREAD

**Issue by vasyakrg** [k0sproject/k0smotron#868]
How to specify cluster name correctly so that when kubeconfig is formed it will be written in context ? 

I do this: 

```
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
   name: first-kube
   namespace: first-kube
spec:
  replicas: 3
  version: v1.31.3
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: first-kube
``` 

that is, I try to pass through metadata, but in kubeconfig still only `k0s`
